name: Flowzone

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - "main"
      - "master"

jobs:
  flowzone:
    name: Flowzone
    uses: product-os/flowzone/.github/workflows/flowzone.yml@master
    secrets: inherit
    with:
      balena_slugs: 'balenalabs/connector,balenalabs/connector-aarch64,balenalabs/connector-armv7hf,balenalabs/connector-amd64'
